language: node_js

node_js:
  - "stable"
  - "8"
  - "6"

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v[0-9].*$/

script:
  - npm run test:output
  - npm run test:runner

env:
  global:
    - secure: "UJdwqR96barkN6NSHUJ/wiA2HmweS8thbklMtvzjMFJ1mmImcEaolHtYT7rRIC8gKl2BE8FK/uPKK05pSOd5ZWN+4STAGubscba4Eg5kBdmaREL5FgR5H71fn2Iuu3iSBxMfOX2fmGR7SBpPvEsMkYwusnsbBKxV69qQaSVgoJD39wgjWE329beH8Pef6GsEcle3rDt+5W1ljmQfX4jOW9o9VTyZKM8lK0JZcvDxC31J7g87Bn8VGYOgG23USAfVtWqiWB+EZlTkOM/qsj9hQc2BuBw551cgOZ+m1Rcn/KkVmn1+pjqfyHgYNqL88T5t10w8bt7Gfbq3URbEg2gEQWspRFe481zzNYEkCdZku7CEetjxjtV49BMmw/5k62SJVGL02wWzigwwM+EUVOyiCacNJHAoGaeASxxl1WXs08d9wnNfGOYA8qeDXn1m0vWFILRckWE9GjqcAxsruIbdXZEd14SDJ7arzc/dv97E1QIi7BaAueV2/0iVLVjtosCqSSFxrDgFeeOwZ9eS77N6/AHzrC9CeZd9jucTzkJGsX6YZmpQvLtjuDCENYFitdLbedZMg8ga2gibdkwdUaSNCZlpW63MfpexVmz9vi/wpZns/ZQJlauLUwFpV5J17zUzKEWSoZ6Wi4Cw/90uF3cFziFraPyDb5yOiD5nGMcsQck="
    - secure: "bSpLwMm2q8og40ylt/E/duFqbd2FLxhHRM2uTmNnsmNT6DkfeLzHVg9VhOWPzC4QrjQyIsA374sv4fUbhEHuOsBAV/VGKE65BhLmKkksGZbS6ALocw4rPcIV1+IqPQ/pBvXLhvHWvcGqAxo/AzkZrWGfNJHoWkxcGYwvTCiFByL4/deCfTzdI8SfLLu2CesaNbVOuTnEY8LWl4GliT0SgbgpDp2Lo8ZkM87HSp+71XxU5P0OS65DXBDAO7tJHvPuc0NcVMdNoYSFxw9XPNpoMrGQl3xHP65vo3YWdxjSGjQkyQdLawq8L1WQ+CBfJ2cWdX51g+8k6q0RjudMSS33rBtEZFnexieKqRdHT8NJB3YfuCPZ7aOVhM038677jkYiIv25a4uh/a6ysJSIoPgMdhGcYjpFQ3MtDrQxR3aTV6h/acvdbEaxD/MPHt1KlEThv2ItycAVyqOwFJeEc0mmLGtBXmY/nabKBfxCiQiDxkSaDHdjYC1Tc6K5t5UBeThnpMCiJZaFIMYrDx2LXDE2InVIeVlXR5Vj9A1UxM4exgfA/USwtz0rWw+PnY7q7tNm+c3UZiYzleofy7ztF6iHqvrCjIE67mIFrk/TuptiJsne2MWOTuIZvIXeL+t5zmpgk+OhqJmfcUHWAzDY2acyPXjvsoqwWfiKL7qiNzswWpM="